server:
  port: 8090
  servlet:
    context-path: /api/v1

admin:
  server:
    prefix: /api/v1/server-admin

spring:
  application:
    name: admin-service

#springdoc:
#  swagger-ui:
#    config-url: /admin-service/api/v1/v3/api-docs/swagger-config
#    url: /admin-service/api/v1/v3/api-docs
