server:
  port: 8090
  servlet:
    context-path: /api/v1

admin:
  server:
    prefix: /api/v1/server-admin

spring:
  application:
    name: admin-service
  zipkin:
    base-url: http://k8a806.p.ssafy.io:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

#springdoc:
#  swagger-ui:
#    config-url: /admin-service/api/v1/v3/api-docs/swagger-config
#    url: /admin-service/api/v1/v3/api-docs
