server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8000/
          predicates:
            - Path=/user-service/**
#          filters:
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: payment-service
          uri: http://localhost:8001/
          predicates:
            - Path=/payment-service/**
#          filters:
#            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
