# Payment Server Portitelabel Error Page
server:
  port: 0
  servlet:
    context-path: /api/v1

# JPA Settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true

  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/ssafy806_payment
    username: ssafy806
    password: ssafy806

# user-service url
#user:
#  server:
#    url: http://localhost:8000
#    prefix: /api/v1/payment

# Kakao Pay Setting
kakao:
  host: https://kapi.kakao.com
  app-key: e6444dbd88ac593b0ef5afd9b6d63bd1

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka