server:
  port: 8001
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: default
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: ${job.name:NONE}
  datasource:
    url: jdbc:mysql://localhost:3306/ssafy806_payment
    username: ssafy806
    password: ssafy806

user:
  server:
    url: http://localhost:8000
    prefix: /api/v1/server-payment

concert:
  server:
    url: http://localhost:8002
    prefix: /api/v1/server-payment

# Kakao Pay Setting
kakao:
  host: https://kapi.kakao.com
  app-key: e6444dbd88ac593b0ef5afd9b6d63bd1

#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    config-url: /payment-service/api/v1/v3/api-docs/swagger-config
    url: /payment-service/api/v1/v3/api-docs
